### ISSUE TITLE
look for templates for chatbot

### ISSUE THREAD

**Issue by 1tracy** [1tracy/mental-health-assistant#18]

**Comment by AngelynDisguise** [comment]
I thought of trying to follow this to add a chatbot https://www.youtube.com/watch?v=C3JKS3a4R5Y
I'm not sure how to add this to react though...

**Comment by AngelynDisguise** [comment]
https://medium.com/@awaisshaikh94/chat-component-built-with-react-and-material-ui-c2b0d9ccc491

Here's a template with the code, but the whole window looks like it's the chat component and doesn't pop up quite like I'd like it to  like in the tutorial I saw. Any ideas?
